version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd "$CODEBUILD_SRC_DIR/$FRONTEND_APP_DIR"
      - npm ci
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/$FRONTEND_APP_DIR"
      - SITE_URL="$SITE_URL" npm run build
      - npm run check
