import fs from 'node:fs';
const data = JSON.parse(fs.readFileSync(new URL('./aggregate-results.json', import.meta.url), 'utf8'));
const rows = data.aggregates.filter(row => row.scenario === 'heterogeneous');
const colors = {uniform: '#67e8f9', risk_weighted: '#f59e0b', balanced: '#a78bfa'};
const labels = {uniform: 'Population sample', risk_weighted: 'Risk weighted', balanced: 'Balanced strata'};
const bars = rows.map((row, index) => {
  const x = 110 + index * 250;
  const height = row.criticalDetectionPower * 200;
  const y = 355 - height;
  return `<g><rect x="${x}" y="${y.toFixed(1)}" width="150" height="${height.toFixed(1)}" rx="8" fill="${colors[row.policy]}"/><text x="${x + 75}" y="${(y - 16).toFixed(1)}" text-anchor="middle" class="value">${(row.criticalDetectionPower * 100).toFixed(1)}%</text><text x="${x + 75}" y="390" text-anchor="middle" class="label">${labels[row.policy]}</text><text x="${x + 75}" y="416" text-anchor="middle" class="small">critical n=${row.meanCriticalN.toFixed(0)} · N_eff=${row.effectiveNMean.toFixed(0)}</text></g>`;
}).join('');
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540" viewBox="0 0 960 540" role="img" data-visual-quality="publication" data-text-fit="bounded"><title>Critical regression detection power by canary sampling policy</title><desc>Risk-weighted and balanced sampling sharply increase detection power for a one-percent critical stratum, while reducing effective population sample size.</desc><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#081426"/><stop offset="1" stop-color="#152238"/></linearGradient></defs><rect width="960" height="540" fill="url(#bg)"/><text x="64" y="58" class="title">Rare regressions disappear in population samples</text><text x="64" y="88" class="subtitle">4,000 repeats · 400 paired cases · one-sided exact sign test · heterogeneous confirmatory scenario</text><line x1="74" y1="355" x2="875" y2="355" stroke="#64748b"/><line x1="74" y1="155" x2="875" y2="155" stroke="#334155" stroke-dasharray="5 6"/><text x="52" y="360" class="axis">0%</text><text x="42" y="161" class="axis">100%</text>${bars}<rect x="66" y="454" width="828" height="54" rx="8" fill="#0f1f34" stroke="#334155"/><text x="86" y="478" class="note">Detection and estimation are different jobs:</text><text x="86" y="499" class="small">risk weighting finds the critical regression; inverse-probability weights are still required for population prevalence.</text><style>.title{font:700 28px ui-monospace,SFMono-Regular,Menlo,monospace;fill:#f8fafc}.subtitle,.label,.small,.axis,.note,.value{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.subtitle{font-size:13px;fill:#94a3b8}.label{font-size:15px;font-weight:700;fill:#e2e8f0}.small{font-size:12px;fill:#94a3b8}.axis{font-size:12px;fill:#94a3b8}.note{font-size:14px;font-weight:700;fill:#f8fafc}.value{font-size:22px;font-weight:800;fill:#f8fafc}</style></svg>`;
fs.writeFileSync(new URL('./risk-weighted-canary-results.svg', import.meta.url), svg);
